version: "3"
    
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DB: wordpressDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_volume:/var/lib/mysql
  
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB: wordpressDatabase
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASS: mypassword
    volumes:
      - wordpress_volume:/var/www/html
volumes:
  mysql_volume: {}
  wordpress_volume: {}